version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    volumes:
    - essentials_database:/var/lib/mysql
    
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  essentials_database: